global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: "flink"
    static_configs:
      - targets: ["flink-jobmanager:9249", "flink-taskmanager:9249"]

  - job_name: "simulator"
    static_configs:
      - targets: ["simulator:8001"]
