apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: TimescaleDB
    type: postgres
    access: proxy
    uid: timescaledb
    url: timescaledb:5432
    database: iot_data
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    editable: true
